### ISSUE TITLE
trusted roots 

### ISSUE THREAD

**Issue by fitsum** [Busindre/How-to-Add-trusted-root-certificates#2]
MacOS instructions work perfectly
Tried Ubuntu instructions for ChromeOS' linux beta but I still get invalid cert warning. Any insight as to why?

**Comment by Busindre** [comment]
You can try the documentation in these links. If you get it let me know and we will add it to the Readme.

https://support.google.com/chrome/a/answer/3505249?hl=en&ref_topic=3504941
https://support.n4l.co.nz/s/article/Installing-an-SSL-Certificate-on-a-Chromebook-Manually
